#ignored = ["github.com/lancer-kit/armory"]

[[constraint]]
  name = "github.com/Masterminds/squirrel"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lancer-kit/armory"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
